PUT http://localhost:3001/api/stories/1/entries/edit/21
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoidGVzdGVyIiwiZW1haWwiOiJ0ZXN0ZXJAdGVzdC5jb20iLCJpYXQiOjE2MDc3OTcyNTksImV4cCI6MTYwODQwMjA1OX0.5JPcsCopBptNCgQfU4NAsrm9BPMJjnVcr23p513KNHw

{
    "title": "Testing If i can edit this",
    "description": "Entries man Objection and shiz",
    "date":"May 22, 1911",
    "embed": "google.com/suicidewatch",
    "hashtags": [{"tagname":"hu"},{"tagname":"ma"},{"tagname":"n"}],
    "format_id": 2
}

#####

DELETE http://localhost:3001/api/stories/10/entries/22
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiaGVjdG9yIiwiZW1haWwiOiJoZWN0b3JAZ21haWwuY29tIiwiaWF0IjoxNjA2ODc4MDE1LCJleHAiOjE2MDY5NjQ0MTV9.9Mjj-8a1SyldxM_SHxFc_FwfewwgHyYeU11fKYnybUg
#####

POST http://localhost:3001/api/stories/1/entries
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoidGVzdGVyIiwiZW1haWwiOiJ0ZXN0ZXJAdGVzdC5jb20iLCJpYXQiOjE2MDc3OTYxMTYsImV4cCI6MTYwODQwMDkxNn0.zD2oqGvEqFhI5JncdjJ6cw4iIf40uvib5zz03VwVJUY

{
    "title": "yeppp Testman sucks",
    "description": "You stink",
    "date":"2020-11-28",
    "embed": "somtext",
    "format_id": 2,
    "hashtags": [{"tagname":"love"},{"tagname":"cool"},{"tagname":"niceday"}]
}


#####

GET http://localhost:3001/api/stories/1/entries/15
Content-Type: application/json