GET http://localhost:3001/api/profile/4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0bWFuQGdtYWlsLmNvbSIsImlhdCI6MTYwNzEzNTczMCwiZXhwIjoxNjA3MjIyMTMwfQ.ux-uavdbXH9hFDSkC3icFfDze5HSIc9K6gCLMpdaGfg

#####
GET http://localhost:3001/api/profile/1