POST http://localhost:3001/api/stories/create
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiaGVjdG9yIiwiZW1haWwiOiJoZWN0b3JAZ21haWwuY29tIiwiaWF0IjoxNjA2OTM0MDEyLCJleHAiOjE2MDcwMjA0MTJ9.4CEMxfPavUAK2N6XxaWTXY1XQ3gZq7O2xr54bUBhtOs

{
    "title": "Never forget your relation and look at your ERD",
    "date": "2020-01-02"
}

#####

GET http://localhost:3001/api/stories
Content-Type: application/json


#####
GET http://localhost:3001/api/stories/2
Content-Type: application/json

#####
PUT http://localhost:3001/api/stories/edit/11
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiaGVjdG9yIiwiZW1haWwiOiJoZWN0b3JAZ21haWwuY29tIiwiaWF0IjoxNjA2ODQyMDI2LCJleHAiOjE2MDY5Mjg0MjZ9.hCraUhHd8svBgUxjDA_SCme5ei3faD31Xp9BcSWTob4

{
    "title":"Got my first job"
}

#####
DELETE http://localhost:3001/api/stories/11
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiaGVjdG9yIiwiZW1haWwiOiJoZWN0b3JAZ21haWwuY29tIiwiaWF0IjoxNjA2OTM0MzY3LCJleHAiOjE2MDcwMjA3Njd9.LHeiyuzZn0L9YYSl5ETdAQ37mC8_myyABl4r3bp41EQ