module.exports = [
  {
    story_id: 0,
    format_id: 1,
    title: 'i started school',
    date: '2020-1-21',
    description: 'school is the bomb',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 0,
    format_id: 3,
    title: 'got my first gf',
    date: '2020-1-21',
    description: 'Met her at a diner, gave her my number',
    embed: 'text',
  },
  {
    story_id: 1,
    format_id: 1,
    title: 'Going Fast',
    date: '2020-1-21',
    description: 'Did mad burnouts in the parking lot',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 1,
    format_id: 1,
    title: 'Got a ticket',
    date: '2020-1-21',
    description: 'I din do nuffin!',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 2,
    format_id: 1,
    title: 'We said i do',
    date: '2020-1-21',
    description: 'The best day of my life we got married in Cancun!!',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 2,
    format_id: 1,
    title: 'Honeymoon life',
    date: '2020-1-21',
    description: 'Got to go to fiji!!! CHeck us out',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 3,
    format_id: 1,
    title: 'work is awesome',
    date: '2020-1-21',
    description: 'I got to see how a computer works',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 3,
    format_id: 1,
    title: 'Started learning COBOL',
    date: '2020-1-21',
    description: 'This stuff is like english, i would have never thought',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 4,
    format_id: 1,
    title: 'Got a dog',
    date: '2020-1-21',
    description:
      'check out my dog here chillin and sleeping. Basically he does nothing',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 4,
    format_id: 1,
    title: 'Dog got rabies',
    date: '2020-1-21',
    description:
      'Now i have to take him to the vet. Dr.Scheme said his ticker aint working too well.',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 5,
    format_id: 1,
    title: 'I am so sad',
    date: '2020-1-21',
    description: 'I have no milk for my cereal. this really sucks',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 5,
    format_id: 1,
    title: 'guess what?',
    date: '2020-1-21',
    description: 'I had a bad dream, i had no shoes',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 6,
    format_id: 1,
    title: 'Im fkn rich!!!',
    date: '2020-1-21',
    description: 'No more taking the bus for me',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 6,
    format_id: 1,
    title: 'Check me out',
    date: '2020-1-21',
    description: 'I got a gold toilet AND bidet',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 7,
    format_id: 1,
    title: 'Me during the baptizing',
    date: '2020-1-21',
    description: 'I got water on me!!',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 7,
    format_id: 1,
    title: 'Priest life',
    date: '2020-1-21',
    description: 'Priest shook my hand and i got a certificate',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 8,
    format_id: 1,
    title: 'Im cold',
    date: '2020-1-21',
    description:
      'I dont know man. The leader asked me to get naked. What you think?',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 8,
    format_id: 1,
    title: 'This is weird',
    date: '2020-1-21',
    description: 'I had some kool-aid and it tasted funny',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 9,
    format_id: 1,
    title: 'What i drank',
    date: '2020-1-21',
    description:
      'Had too many choices, Cristal, Don perginon, the odds are endless',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 9,
    format_id: 1,
    title: 'Me sleeping',
    date: '2020-1-21',
    description: 'alcohol comforts me dawg',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
]
