module.exports = [
  {
    story_id: 1,
    format_id: 1,
    title: 'I remember when you crashed dawg, be careful',
    date: '2020-1-21',
    user_id: 1,
    description: 'Next time dude, we are a seatbelt',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 1,
    format_id: 1,
    title: 'Got a ticket',
    date: '2020-1-21',
    user_id: 2,
    description: 'I din do nuffin!',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 2,
    format_id: 1,
    title: 'We said i do',
    user_id: 3,
    date: '2020-1-21',
    description: 'The best day of my life we got married in Cancun!!',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 2,
    format_id: 1,
    title: 'HAHA this dude wasted on the beach honeymoon',
    user_id: 6,
    date: '2020-1-21',
    description: 'here he is ladies and gentleman, litty .',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 3,
    format_id: 1,
    title: 'work is awesome',
    user_id: 3,
    date: '2020-1-21',
    description: 'I got to see how a computer works',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 3,
    format_id: 1,
    title: 'I hate working witht his dude',
    user_id: 2,
    date: '2020-1-21',
    description: 'This stuff is like english, i would have never thought',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 4,
    format_id: 1,
    title: 'Got a dog',
    user_id: 4,
    date: '2020-1-21',
    description:
      'check out my dog here chillin and sleeping. Basically he does nothing',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 4,
    format_id: 1,
    title: 'Your dog and my shoes man!',
    user_id: 7,
    date: '2020-1-21',
    description:
      'I was in a rush to go to work, i put on my shoes and i heard a squish, your dog pooped in my shoes man!!!',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 5,
    format_id: 1,
    title: 'I am so sad',
    user_id: 5,
    date: '2020-1-21',
    description: 'I have no milk for my cereal. this really sucks',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 5,
    format_id: 2,
    title: 'Dont be sad dude, pain is temporary',
    user_id: 4,
    date: '2020-1-21',
    description:
      'Heres a video of me slippin on ice and i cant get up, like DMX said, "im slipping im falling i cant get up"',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 6,
    format_id: 1,
    title: 'Im fkn rich!!!',
    user_id: 6,
    date: '2020-1-21',
    description: 'No more taking the bus for me',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 6,
    format_id: 1,
    title: 'member me? ',
    user_id: 9,
    date: '2020-1-21',
    description:
      'Im your brothers janitors cousin who knows your dad and once i spilled coffee on you, lets reconnect.',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 7,
    format_id: 1,
    title: 'Me during the baptizing',
    user_id: 7,
    date: '2020-1-21',
    description: 'I got water on me!!',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 7,
    format_id: 1,
    title: 'Priest life?',
    user_id: 1,
    date: '2020-1-21',
    description:
      'You all holy now dawg? check this pick from the rippers club last week!',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 8,
    format_id: 1,
    title: 'Im cold',
    user_id: 8,
    date: '2020-1-21',
    description:
      'I dont know man. The leader asked me to get naked. What you think?',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 8,
    format_id: 1,
    title: 'This is weird',
    user_id: 9,
    date: '2020-1-21',
    description: 'I had some kool-aid and it tasted funny',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 9,
    format_id: 1,
    title: 'What i drank',
    user_id: 9,
    date: '2020-1-21',
    description:
      'Had too many choices, Cristal, Don perginon, the odds are endless',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
  {
    story_id: 9,
    format_id: 1,
    title: 'Me sleeping',
    user_id: 6,
    date: '2020-1-21',
    description: 'After seeing your lame af story',
    embed: 'https://i.imgur.com/u4dJKj2.png',
  },
]
