module.exports = [
  {
    author_id: 12,
    name: 'WaylenHunter',
    occupation: 'Staff Gangsta II',
    story_img: 'http://dummyimage.com/195x132.png/5fa2dd/ffffff',
  },
  {
    author_id: 12,
    name: 'Miguel Santos',
    occupation: 'Head Paletero II',
    story_img: 'http://dummyimage.com/195x132.png/5fa2dd/ffffff',
  },
  {
    author_id: 6,
    name: 'Axel',
    occupation: 'Administrative Assistant II',
    story_img: 'http://dummyimage.com/221x245.jpg/cc0000/ffffff',
  },
  {
    author_id: 9,
    name: 'Nedda',
    occupation: 'Staff Scientist',
    story_img: 'http://dummyimage.com/174x150.png/5fa2dd/ffffff',
  },
  {
    author_id: 5,
    name: 'Sunny',
    occupation: 'Database Administrator I',
    story_img: 'http://dummyimage.com/132x228.bmp/5fa2dd/ffffff',
  },
  {
    author_id: 4,
    name: 'James',
    occupation: 'GIS Technical Architect',
    story_img: 'http://dummyimage.com/164x109.jpg/5fa2dd/ffffff',
  },
  {
    author_id: 1,
    name: 'Daffie',
    occupation: 'Staff Scientist',
    story_img: 'http://dummyimage.com/190x139.png/5fa2dd/ffffff',
  },
  {
    author_id: 5,
    name: 'Naomi',
    occupation: 'Associate Professor',
    story_img: 'http://dummyimage.com/202x215.png/cc0000/ffffff',
  },
  {
    author_id: 4,
    name: 'Russell',
    occupation: 'Design Engineer',
    story_img: 'http://dummyimage.com/152x190.jpg/dddddd/000000',
  },
  {
    author_id: 2,
    name: 'Joseph',
    occupation: 'Account Coordinator',
    story_img: 'http://dummyimage.com/168x102.png/ff4444/ffffff',
  },
  {
    author_id: 1,
    name: 'Noland',
    occupation: 'Director of Sales',
    story_img: 'http://dummyimage.com/151x246.bmp/dddddd/000000',
  },
  {
    author_id: 8,
    name: 'Candis',
    occupation: 'Financial Analyst',
    story_img: 'http://dummyimage.com/215x210.png/dddddd/000000',
  },
  {
    author_id: 5,
    name: 'Durant',
    occupation: 'Occupational Therapist',
    story_img: 'http://dummyimage.com/244x224.jpg/5fa2dd/ffffff',
  },
  {
    author_id: 8,
    name: 'Theo',
    occupation: 'Administrative Officer',
    story_img: 'http://dummyimage.com/115x199.jpg/dddddd/000000',
  },
  {
    author_id: 11,
    name: 'Neddie',
    occupation: 'Biostatistician II',
    story_img: 'http://dummyimage.com/201x114.png/dddddd/000000',
  },
  {
    author_id: 9,
    name: 'Waylen',
    occupation: 'Staff Accountant II',
    story_img: 'http://dummyimage.com/195x132.png/5fa2dd/ffffff',
  },
  {
    author_id: 2,
    name: 'Chandra',
    occupation: 'Sales Representative',
    story_img: 'http://dummyimage.com/142x204.bmp/ff4444/ffffff',
  },
  {
    author_id: 12,
    name: 'Anne-marie',
    occupation: 'Human Resources Manager',
    story_img: 'http://dummyimage.com/170x169.jpg/ff4444/ffffff',
  },
  {
    author_id: 6,
    name: 'Taber',
    occupation: 'Statistician II',
    story_img: 'http://dummyimage.com/128x222.png/5fa2dd/ffffff',
  },
  {
    author_id: 10,
    name: 'Lotty',
    occupation: 'Quality Engineer',
    story_img: 'http://dummyimage.com/137x190.bmp/5fa2dd/ffffff',
  },
  {
    author_id: 1,
    name: 'Johnnie',
    occupation: 'Pharmacist',
    story_img: 'http://dummyimage.com/192x145.jpg/5fa2dd/ffffff',
  },
  {
    author_id: 6,
    name: 'Rollin',
    occupation: 'Project Manager',
    story_img: 'http://dummyimage.com/189x161.jpg/dddddd/000000',
  },
]
