module.exports = [
  {
    author_id: 12,
    name: 'WaylenHunter',
    occupation: 'Staff Gangsta II',
    story_img: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    author_id: 12,
    name: 'Miguel Santos',
    occupation: 'Head Paletero II',
    story_img: 'https://randomuser.me/api/portraits/men/4.jpg',
  },
  {
    author_id: 6,
    name: 'Axel',
    occupation: 'Administrative Assistant II',
    story_img: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    author_id: 9,
    name: 'Nedda',
    occupation: 'Staff Scientist',
    story_img: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
  {
    author_id: 5,
    name: 'Sunny',
    occupation: 'Database Administrator I',
    story_img: 'https://randomuser.me/api/portraits/men/20.jpg',
  },
  {
    author_id: 4,
    name: 'James',
    occupation: 'GIS Technical Architect',
    story_img: 'https://randomuser.me/api/portraits/men/14.jpg',
  },
  {
    author_id: 1,
    name: 'Daffie',
    occupation: 'Staff Scientist',
    story_img: 'https://randomuser.me/api/portraits/women/30.jpg',
  },
  {
    author_id: 5,
    name: 'Naomi',
    occupation: 'Associate Professor',
    story_img: 'https://randomuser.me/api/portraits/women/28.jpg',
  },
  {
    author_id: 4,
    name: 'Russell',
    occupation: 'Design Engineer',
    story_img: 'https://randomuser.me/api/portraits/men/33.jpg',
  },
  {
    author_id: 2,
    name: 'Joseph',
    occupation: 'Account Coordinator',
    story_img: 'https://randomuser.me/api/portraits/men/22.jpg',
  },
  {
    author_id: 1,
    name: 'Noland',
    occupation: 'Director of Sales',
    story_img: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    author_id: 8,
    name: 'Candis',
    occupation: 'Financial Analyst',
    story_img: 'https://randomuser.me/api/portraits/women/17.jpg',
  },
  {
    author_id: 5,
    name: 'Durant',
    occupation: 'Occupational Therapist',
    story_img: 'https://randomuser.me/api/portraits/men/25.jpg',
  },
  {
    author_id: 8,
    name: 'Theo',
    occupation: 'Administrative Officer',
    story_img: 'https://randomuser.me/api/portraits/men/39.jpg',
  },
  {
    author_id: 11,
    name: 'Neddie',
    occupation: 'Biostatistician II',
    story_img: 'https://randomuser.me/api/portraits/women/26.jpg',
  },
  {
    author_id: 9,
    name: 'Waylen',
    occupation: 'Staff Accountant II',
    story_img: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    author_id: 2,
    name: 'Chandra',
    occupation: 'Sales Representative',
    story_img: 'https://randomuser.me/api/portraits/women/14.jpg',
  },
  {
    author_id: 12,
    name: 'Anne-marie',
    occupation: 'Human Resources Manager',
    story_img: 'https://randomuser.me/api/portraits/women/7.jpg',
  },
  {
    author_id: 6,
    name: 'Taber',
    occupation: 'Statistician II',
    story_img: 'https://randomuser.me/api/portraits/men/34.jpg',
  },
  {
    author_id: 10,
    name: 'Lotty',
    occupation: 'Quality Engineer',
    story_img: 'https://randomuser.me/api/portraits/women/7.jpg',
  },
  {
    author_id: 1,
    name: 'Johnnie',
    occupation: 'Pharmacist',
    story_img: 'https://randomuser.me/api/portraits/men/4.jpg',
  },
  {
    author_id: 6,
    name: 'Rollin',
    occupation: 'Project Manager',
    story_img: 'https://randomuser.me/api/portraits/men/29.jpg',
  },
]
